# syntax=docker/dockerfile:1
FROM docker.io/a2rchi/a2rchi-python-base:latest 
RUN mkdir -p /root/archi
WORKDIR /root/archi

COPY LICENSE LICENSE

#EXPOSE 7861

# ensure this directory is present for prod-801 deployment
# RUN if [ "$BUILD_ENV" = "prod-801" ] ; then mkdir /root/data/801-content ; fi

RUN apt-get update && apt-get install -y \
    ca-certificates \
    git \
    wget \
    gnupg \
    --no-install-recommends \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


COPY archi_code src
COPY configs configs
COPY pyproject.toml pyproject.toml
COPY weblists weblists
RUN pip install --upgrade pip && pip install .

RUN chmod g+rx /root; chmod -R g+w /root/archi/src/interfaces

ARG APP_VERSION=unknown
ENV APP_VERSION=${APP_VERSION}

CMD ["python", "-u", "src/bin/service_chat.py"]
